/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica se a API está no ar (sem autenticação) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dados do usuário da área Jotanunes identificado pelo token (perfil, origem e troca pendente)
         * @description Responde também com troca de senha pendente (login próprio), para o front mostrar a tela de troca.
         */
        get: operations["fluigObterUsuarioAtual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/auth/configuracao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diz se o login próprio da área Jotanunes está ligado (anônimo)
         * @description Sempre 200, sem autenticação, com `Cache-Control: no-store`. O front chama quando não tem
         *     token: `true` → tela de login; `false` → "Abra este sistema pelo Fluig.".
         */
        get: operations["fluigObterConfiguracaoAcesso"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login próprio da área Jotanunes (login + senha de usuário interno)
         * @description Anônimo, com limite de 10 requisições/min por IP (mesma regra do login do portal).
         *     Login sem diferenciar maiúsculas (espaços nas pontas removidos).
         *     5 falhas seguidas no mesmo login — existente ou não — → bloqueio de 15 min (423 `ACESSO_BLOQUEADO`).
         *     `LOGIN_INVALIDO` não revela se o login existe (mesma mensagem e mesma sequência de respostas).
         *     Com senha provisória, a sessão volta com `usuario.trocaSenhaObrigatoria=true`.
         *     Login próprio desligado → 404 `NAO_ENCONTRADO`.
         */
        post: operations["fluigLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/auth/trocar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Troca a senha do usuário interno (obrigatória no primeiro acesso) e devolve nova sessão
         * @description Só para sessão de login próprio (token Fluig → 409 `SO_LOGIN_LOCAL`). Permitida com
         *     `troca_senha=true`. Exige a senha atual; nova senha com 8–128 caracteres, letra e número,
         *     diferente da atual. Incrementa a versão da credencial (tokens anteriores deixam de valer) e
         *     devolve novo token com `troca_senha=false`. Login próprio desligado → 404.
         */
        post: operations["fluigTrocarSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/auth/sair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerra a sessão de login próprio (revoga o token na hora)
         * @description Incrementa a versão da credencial do usuário interno: o token atual (e outras sessões do mesmo
         *     usuário) passam a 401. Com token do Fluig → 204 sem efeito. Permitida com troca de senha
         *     pendente. Login próprio desligado → 404.
         */
        post: operations["fluigSair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/painel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indicadores do painel inicial (US5) */
        get: operations["fluigObterPainel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/obras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista obras (ordenadas por nome) */
        get: operations["fluigListarObras"];
        put?: never;
        /** Cadastra obra */
        post: operations["fluigCriarObra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/obras/{obraId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obraId: components["parameters"]["ObraId"];
            };
            cookie?: never;
        };
        /** Detalhe da obra com empresas vinculadas e contagem de documentos */
        get: operations["fluigObterObra"];
        /** Atualiza obra (inclui ativar/desativar) */
        put: operations["fluigAtualizarObra"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/obras/{obraId}/empresas/{empresaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obraId: components["parameters"]["ObraId"];
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Vincula a empresa à obra (idempotente) */
        put: operations["fluigVincularEmpresaObra"];
        post?: never;
        /** Remove o vínculo da empresa com a obra */
        delete: operations["fluigDesvincularEmpresaObra"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/empresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista empresas (ordenadas por razão social) */
        get: operations["fluigListarEmpresas"];
        put?: never;
        /** Cadastra empresa terceirizada */
        post: operations["fluigCriarEmpresa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/empresas/{empresaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        /** Detalhe da empresa */
        get: operations["fluigObterEmpresa"];
        /**
         * Atualiza empresa (inclui ativar/desativar)
         * @description Desativar incrementa a versão da credencial (sessões do portal caem na hora).
         *     Alterar o CNPJ depois do 1º convite → 409 `CNPJ_IMUTAVEL`.
         */
        put: operations["fluigAtualizarEmpresa"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/empresas/{empresaId}/convites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        /** Histórico de convites da empresa (mais recente primeiro) */
        get: operations["fluigListarConvites"];
        put?: never;
        /**
         * Envia (ou reenvia) o convite por e-mail
         * @description Permitido aos dois perfis (administrador e comum).
         *     Gera token de link (7 dias) e senha temporária, invalida convites anteriores, redefine o
         *     acesso (troca de senha obrigatória) e envia o e-mail ao `emailContato`.
         *     Se o e-mail falhar, nada é gravado (502 `EMAIL_FALHOU`).
         */
        post: operations["fluigEnviarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/empresas/{empresaId}/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        /** Situação de cada tipo de documento ativo para a empresa (ordenado por nome do tipo) */
        get: operations["fluigListarDocumentosEmpresa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/empresas/{empresaId}/documentos/{tipoDocumentoId}/envios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        /** Histórico de envios da empresa para o tipo (mais recente primeiro; inclui tipos inativos) */
        get: operations["fluigListarHistoricoEnvios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/tipos-documento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista tipos de documento (ordenados por nome; sem paginação) */
        get: operations["fluigListarTiposDocumento"];
        put?: never;
        /** Cadastra tipo de documento (passa a ser exigido de todas as empresas ativas) */
        post: operations["fluigCriarTipoDocumento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/tipos-documento/{tipoDocumentoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        /** Detalhe do tipo de documento */
        get: operations["fluigObterTipoDocumento"];
        /** Atualiza tipo de documento (inclui ativar/desativar) */
        put: operations["fluigAtualizarTipoDocumento"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/envios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fila de análise / busca de envios
         * @description Padrão `status=EM_ANALISE`, ordenado do envio mais antigo para o mais novo.
         *     Para `APROVADO`/`REJEITADO`, ordenado do mais recente para o mais antigo.
         */
        get: operations["fluigListarEnvios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/envios/{envioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        /** Detalhe de um envio */
        get: operations["fluigObterEnvio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/envios/{envioId}/arquivo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        /** Baixa o arquivo do envio (registra auditoria ARQUIVO_BAIXADO) */
        get: operations["fluigBaixarArquivoEnvio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/envios/{envioId}/aprovar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprova um envio EM_ANALISE */
        post: operations["fluigAprovarEnvio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/envios/{envioId}/rejeitar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rejeita um envio EM_ANALISE com motivo (envia e-mail de aviso à empresa) */
        post: operations["fluigRejeitarEnvio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuários internos (ordenados por nome) */
        get: operations["fluigListarUsuariosInternos"];
        put?: never;
        /**
         * Cadastra usuário interno e envia a senha provisória por e-mail
         * @description Gera senha provisória (12 caracteres, vale 7 dias, troca obrigatória no primeiro acesso) e
         *     envia o e-mail de acesso ao `email`. A senha NUNCA volta na resposta. Se o e-mail falhar,
         *     nada é gravado (502 `EMAIL_ACESSO_FALHOU`).
         */
        post: operations["fluigCriarUsuarioInterno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/usuarios/{usuarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: components["parameters"]["UsuarioId"];
            };
            cookie?: never;
        };
        /** Detalhe do usuário interno */
        get: operations["fluigObterUsuarioInterno"];
        /**
         * Atualiza nome, e-mail, perfil e ativação do usuário interno (o login não muda)
         * @description Mudar `admin` ou `ativo` revoga na hora as sessões do usuário (versão da credencial + 1).
         *     Recusas: a sessão de login próprio desativando a si mesma ou tirando o próprio papel →
         *     409 `ALTERACAO_PROPRIA_NAO_PERMITIDA`; deixaria o sistema sem nenhum usuário interno
         *     administrador ativo → 409 `ULTIMO_ADMINISTRADOR`.
         */
        put: operations["fluigAtualizarUsuarioInterno"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluig/usuarios/{usuarioId}/redefinir-senha": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: components["parameters"]["UsuarioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gera nova senha provisória e envia por e-mail
         * @description Nova senha provisória (7 dias, troca obrigatória), zera tentativas/bloqueio e revoga as
         *     sessões do usuário. Usuário desativado → 409 `USUARIO_INATIVO`. Se o e-mail falhar, nada
         *     muda (502 `EMAIL_ACESSO_FALHOU`). A senha NUNCA volta na resposta.
         */
        post: operations["fluigRedefinirSenhaUsuarioInterno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/convites/validar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valida o link do convite e devolve dados para pré-preencher a tela de acesso
         * @description Anônimo, com limite de 10 requisições/min por IP.
         *     O token do convite é um segredo de acesso: vai no CORPO da requisição (nunca no caminho nem na
         *     query string), para não aparecer em logs de proxy/servidor, histórico ou cabeçalhos `Referer`.
         *     Token ausente, vazio ou fora do tamanho → 404 `CONVITE_INVALIDO` (mesma resposta de um token inexistente);
         *     400 `VALIDACAO` só quando o corpo não é um JSON legível.
         */
        post: operations["portalValidarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acesso da empresa por CNPJ + senha
         * @description Anônimo, com limite de 10 requisições/min por IP.
         *     5 falhas seguidas no mesmo CNPJ → bloqueio de 15 min (423 `ACESSO_BLOQUEADO`).
         *     Mensagem de `CREDENCIAIS_INVALIDAS` não revela se o CNPJ existe.
         */
        post: operations["portalLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/auth/trocar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Troca a senha (obrigatória no primeiro acesso) e devolve nova sessão
         * @description Permitida com `troca_senha=true`. Marca o convite como usado, incrementa a versão da
         *     credencial (tokens anteriores deixam de valer) e devolve novo token com `troca_senha=false`.
         */
        post: operations["portalTrocarSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da empresa autenticada (permitido com troca de senha pendente) */
        get: operations["portalObterEmpresaAtual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Documentos exigidos da empresa autenticada e a situação de cada um
         * @description Todos os tipos ativos, ordenados por situação (REJEITADO, PENDENTE_ENVIO, EM_ANALISE, APROVADO) e nome.
         */
        get: operations["portalListarDocumentos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/documentos/{tipoDocumentoId}/envios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        /** Histórico de envios da própria empresa para o tipo (mais recente primeiro) */
        get: operations["portalListarHistoricoEnvios"];
        put?: never;
        /**
         * Envia arquivo para o tipo de documento (PDF, JPEG ou PNG, até 10 MB)
         * @description Permitido somente quando a situação é `PENDENTE_ENVIO` ou `REJEITADO` e o tipo está ativo.
         *     O formato é validado pelo conteúdo do arquivo (assinatura de bytes), não pela extensão.
         */
        post: operations["portalEnviarDocumento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/envios/{envioId}/arquivo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        /** Baixa arquivo de um envio da própria empresa (outra empresa → 404) */
        get: operations["portalBaixarArquivoEnvio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description | code | status | mensagem padrão (title) |
         *     |---|---|---|
         *     | VALIDACAO | 400 | Confira os dados informados. |
         *     | NAO_AUTENTICADO | 401 | Sua sessão expirou. Entre de novo. |
         *     | TROCA_SENHA_OBRIGATORIA | 403 | Crie uma nova senha para continuar. (portal e login próprio da área Jotanunes) |
         *     | SEM_PERMISSAO | 403 | Só administradores podem fazer isso. Se você precisa, fale com a TI. |
         *     | NAO_ENCONTRADO | 404 | Não encontramos o que você procurou. |
         *     | CNPJ_DUPLICADO | 409 | Já existe uma empresa com este CNPJ. |
         *     | CNPJ_IMUTAVEL | 409 | O CNPJ não pode ser alterado depois do convite. |
         *     | CODIGO_OBRA_DUPLICADO | 409 | Já existe uma obra com este código. |
         *     | NOME_DUPLICADO | 409 | Já existe um tipo de documento com este nome. |
         *     | EMPRESA_INATIVA | 409 (Fluig) / 403 (login) | Esta empresa está desativada. |
         *     | CREDENCIAIS_INVALIDAS | 401 | CNPJ ou senha incorretos. |
         *     | ACESSO_BLOQUEADO | 423 | Muitas tentativas. Tente de novo em 15 minutos. (portal e login próprio) |
         *     | CONVITE_INVALIDO | 404 | Este link não é mais válido. |
         *     | CONVITE_EXPIRADO | 401 | Seu convite expirou. Peça um novo convite à Jotanunes. |
         *     | SENHA_FRACA | 400 | A senha precisa ter pelo menos 8 caracteres, com letras e números. |
         *     | SENHA_ATUAL_INCORRETA | 400 | A senha atual não confere. |
         *     | ENVIO_NAO_PERMITIDO | 409 | Este documento já está em análise ou aprovado. |
         *     | ENVIO_JA_ANALISADO | 409 | Este envio já foi analisado. |
         *     | ARQUIVO_INVALIDO | 400 | Não conseguimos ler este arquivo. |
         *     | ARQUIVO_MUITO_GRANDE | 413 | O arquivo passa de 10 MB. |
         *     | ARQUIVO_TIPO_NAO_SUPORTADO | 415 | Envie um arquivo PDF, JPG ou PNG. |
         *     | EMAIL_FALHOU | 502 | Não conseguimos enviar o convite. Tente de novo em alguns minutos. |
         *     | LIMITE_REQUISICOES | 429 | Muitas tentativas. Aguarde um pouco. |
         *     | ERRO_INTERNO | 500 | Algo deu errado do nosso lado. Tente de novo. |
         *     | LOGIN_INVALIDO | 401 | Login ou senha incorretos. |
         *     | USUARIO_INATIVO | 403 (login) / 409 (redefinir senha) | Este usuário está desativado. Fale com um administrador do sistema. |
         *     | SENHA_PROVISORIA_EXPIRADA | 401 | Sua senha provisória expirou. Peça a um administrador para gerar outra. |
         *     | LOGIN_DUPLICADO | 409 | Já existe um usuário com este login. |
         *     | ULTIMO_ADMINISTRADOR | 409 | O sistema precisa de pelo menos um administrador ativo. |
         *     | ALTERACAO_PROPRIA_NAO_PERMITIDA | 409 | Você não pode desativar nem tirar o seu próprio acesso de administrador. Peça a outro administrador. |
         *     | EMAIL_ACESSO_FALHOU | 502 | Não conseguimos enviar o e-mail com a senha provisória. Tente de novo em alguns minutos. |
         *     | SO_LOGIN_LOCAL | 409 | Esta opção é só para quem entra com login e senha. |
         * @enum {string}
         */
        CodigoErro: "VALIDACAO" | "NAO_AUTENTICADO" | "TROCA_SENHA_OBRIGATORIA" | "SEM_PERMISSAO" | "NAO_ENCONTRADO" | "CNPJ_DUPLICADO" | "CNPJ_IMUTAVEL" | "CODIGO_OBRA_DUPLICADO" | "NOME_DUPLICADO" | "EMPRESA_INATIVA" | "CREDENCIAIS_INVALIDAS" | "ACESSO_BLOQUEADO" | "CONVITE_INVALIDO" | "CONVITE_EXPIRADO" | "SENHA_FRACA" | "SENHA_ATUAL_INCORRETA" | "ENVIO_NAO_PERMITIDO" | "ENVIO_JA_ANALISADO" | "ARQUIVO_INVALIDO" | "ARQUIVO_MUITO_GRANDE" | "ARQUIVO_TIPO_NAO_SUPORTADO" | "EMAIL_FALHOU" | "LIMITE_REQUISICOES" | "ERRO_INTERNO" | "LOGIN_INVALIDO" | "USUARIO_INATIVO" | "SENHA_PROVISORIA_EXPIRADA" | "LOGIN_DUPLICADO" | "ULTIMO_ADMINISTRADOR" | "ALTERACAO_PROPRIA_NAO_PERMITIDA" | "EMAIL_ACESSO_FALHOU" | "SO_LOGIN_LOCAL";
        Problema: {
            /** @example https://jotanunes.com/problemas/nao-encontrado */
            type: string;
            /** @description Mensagem curta para o usuário (pt-BR). */
            title: string;
            status: number;
            detail?: string | null;
            instance?: string | null;
            code: components["schemas"]["CodigoErro"];
            /** @description Somente em VALIDACAO. Chave = nome do campo (camelCase). */
            errors?: {
                [key: string]: string[];
            } | null;
            /**
             * Format: date-time
             * @description Somente em ACESSO_BLOQUEADO.
             */
            bloqueadoAte?: string | null;
            traceId?: string | null;
        };
        PaginaBase: {
            total: number;
            pagina: number;
            tamanhoPagina: number;
        };
        /** @enum {string} */
        Uf: "AC" | "AL" | "AP" | "AM" | "BA" | "CE" | "DF" | "ES" | "GO" | "MA" | "MT" | "MS" | "MG" | "PA" | "PB" | "PR" | "PE" | "PI" | "RJ" | "RN" | "RS" | "RO" | "RR" | "SC" | "SP" | "SE" | "TO";
        /** @enum {string} */
        SituacaoAcesso: "NAO_CONVIDADA" | "CONVIDADA" | "CONVITE_EXPIRADO" | "ATIVA" | "DESATIVADA";
        /** @enum {string} */
        SituacaoConvite: "VALIDO" | "USADO" | "EXPIRADO" | "SUBSTITUIDO";
        /** @enum {string} */
        StatusEnvio: "EM_ANALISE" | "APROVADO" | "REJEITADO";
        /** @enum {string} */
        SituacaoDocumento: "PENDENTE_ENVIO" | "EM_ANALISE" | "APROVADO" | "REJEITADO";
        /** @enum {string} */
        FormatoArquivo: "application/pdf" | "image/jpeg" | "image/png";
        /**
         * @description Usuário atual da área Jotanunes (nome histórico do schema: desde 1.2.0 representa também a
         *     sessão do login próprio).
         */
        UsuarioFluig: {
            login: string;
            nome: string;
            email: string;
            /**
             * @description true quando o token traz `roles` com `admin`. O front usa para esconder as ações
             *     de administrador; a API confere o papel em toda operação `x-requer-admin`.
             */
            admin: boolean;
            origem: components["schemas"]["OrigemSessao"];
            /** @description Só no login próprio (senha provisória ainda não trocada). Sempre false para o Fluig. */
            trocaSenhaObrigatoria: boolean;
        };
        /**
         * @description `FLUIG` = token emitido pelo Fluig; `LOGIN_LOCAL` = login próprio (mostra "Sair" e "Trocar senha").
         * @enum {string}
         */
        OrigemSessao: "FLUIG" | "LOGIN_LOCAL";
        ConfiguracaoAcesso: {
            loginLocalHabilitado: boolean;
        };
        LoginJotanunesInput: {
            login: string;
            senha: string;
        };
        SessaoJotanunes: {
            /** @description JWT fluigAuth do login próprio (iss=jotanunes-docs). */
            accessToken: string;
            /** Format: date-time */
            expiraEm: string;
            usuario: components["schemas"]["UsuarioFluig"];
        };
        /** @enum {string} */
        SituacaoUsuarioInterno: "AGUARDANDO_PRIMEIRO_ACESSO" | "SENHA_PROVISORIA_EXPIRADA" | "ATIVO" | "DESATIVADO";
        UsuarioInternoInput: {
            /** @description Único sem diferenciar maiúsculas; gravado em minúsculas; não pode ser alterado depois. */
            login: string;
            nome: string;
            /** Format: email */
            email: string;
            /** @default false */
            admin: boolean;
        };
        UsuarioInternoAtualizacao: {
            nome: string;
            /** Format: email */
            email: string;
            admin: boolean;
            ativo: boolean;
        };
        UsuarioInterno: {
            /** Format: uuid */
            id: string;
            login: string;
            nome: string;
            email: string;
            admin: boolean;
            ativo: boolean;
            situacao: components["schemas"]["SituacaoUsuarioInterno"];
            /** Format: date-time */
            senhaProvisoriaExpiraEm?: string | null;
            /**
             * Format: date-time
             * @description Preenchido enquanto o login estiver bloqueado por tentativas erradas.
             */
            bloqueadoAte?: string | null;
            /** Format: date-time */
            ultimoAcessoEm?: string | null;
            /** Format: date-time */
            criadoEm: string;
            /** @description Login de quem cadastrou, ou `sistema` (comando de instalação). */
            criadoPor: string;
            /** Format: date-time */
            atualizadoEm?: string | null;
        };
        PaginaUsuariosInternos: components["schemas"]["PaginaBase"] & {
            itens: components["schemas"]["UsuarioInterno"][];
        };
        AutorFluig: {
            login: string;
            nome: string;
        };
        Painel: {
            enviosEmAnalise: number;
            /** @description Empresas ativas com ao menos um documento PENDENTE_ENVIO ou REJEITADO. */
            empresasComPendencia: number;
            /** @description Empresas com situação CONVIDADA ou CONVITE_EXPIRADO. */
            empresasConvidadasSemAcesso: number;
            empresasAtivas: number;
            obrasAtivas: number;
        };
        ObraInput: {
            nome: string;
            codigo?: string | null;
            cidade: string;
            uf: components["schemas"]["Uf"];
        };
        ObraAtualizacao: components["schemas"]["ObraInput"] & {
            ativa: boolean;
        };
        Obra: {
            /** Format: uuid */
            id: string;
            nome: string;
            codigo?: string | null;
            cidade: string;
            uf: components["schemas"]["Uf"];
            ativa: boolean;
            /** Format: date-time */
            criadoEm: string;
        };
        ObraResumo: components["schemas"]["Obra"] & {
            quantidadeEmpresas: number;
        };
        ObraDetalhe: components["schemas"]["Obra"] & {
            /** @description Empresas vinculadas, ordenadas por razão social. */
            empresas: components["schemas"]["EmpresaNaObra"][];
        };
        ObraRef: {
            /** Format: uuid */
            id: string;
            nome: string;
            cidade: string;
            uf: components["schemas"]["Uf"];
        };
        PaginaObras: components["schemas"]["PaginaBase"] & {
            itens: components["schemas"]["ObraResumo"][];
        };
        EmpresaInput: {
            razaoSocial: string;
            nomeFantasia?: string | null;
            /**
             * @description Com ou sem máscara; numérico ou alfanumérico; DV validado.
             * @example 12.345.678/0001-95
             */
            cnpj: string;
            /** Format: email */
            emailContato: string;
            nomeContato?: string | null;
            /** @description Com ou sem máscara; 10 ou 11 dígitos. */
            telefone?: string | null;
        };
        EmpresaAtualizacao: components["schemas"]["EmpresaInput"] & {
            ativa: boolean;
        };
        ContagemDocumentos: {
            /** @description Tipos de documento ativos. */
            total: number;
            pendentes: number;
            emAnalise: number;
            aprovados: number;
            rejeitados: number;
        };
        EmpresaResumo: {
            /** Format: uuid */
            id: string;
            razaoSocial: string;
            nomeFantasia?: string | null;
            /** @example 12345678000195 */
            cnpj: string;
            emailContato: string;
            ativa: boolean;
            situacaoAcesso: components["schemas"]["SituacaoAcesso"];
            documentos: components["schemas"]["ContagemDocumentos"];
        };
        Empresa: components["schemas"]["EmpresaResumo"] & {
            nomeContato?: string | null;
            /** @description Só dígitos. */
            telefone?: string | null;
            obras: components["schemas"]["ObraRef"][];
            /** @description false depois do primeiro convite. */
            cnpjEditavel: boolean;
            ultimoConvite?: components["schemas"]["Convite"] | null;
            /** Format: date-time */
            ultimoAcessoEm?: string | null;
            /** Format: date-time */
            criadoEm: string;
        };
        EmpresaNaObra: {
            /** Format: uuid */
            empresaId: string;
            razaoSocial: string;
            cnpj: string;
            situacaoAcesso: components["schemas"]["SituacaoAcesso"];
            /** Format: date-time */
            vinculadoEm: string;
            documentos: components["schemas"]["ContagemDocumentos"];
        };
        EmpresaRef: {
            /** Format: uuid */
            id: string;
            razaoSocial: string;
            cnpj: string;
        };
        PaginaEmpresas: components["schemas"]["PaginaBase"] & {
            itens: components["schemas"]["EmpresaResumo"][];
        };
        /** @description Nunca contém o token nem a senha temporária. */
        Convite: {
            /** Format: uuid */
            id: string;
            emailDestino: string;
            /** Format: date-time */
            enviadoEm: string;
            /** Format: date-time */
            expiraEm: string;
            /** Format: date-time */
            usadoEm?: string | null;
            enviadoPor: components["schemas"]["AutorFluig"];
            situacao: components["schemas"]["SituacaoConvite"];
        };
        ConviteValidacaoInput: {
            /** @description Token do link do convite (base64url, 43 caracteres), lido de `?convite=` no portal. */
            token: string;
        };
        ConviteValidacao: {
            cnpj: string;
            razaoSocial: string;
            /** Format: date-time */
            expiraEm: string;
        };
        TipoDocumentoInput: {
            nome: string;
            instrucoes?: string | null;
        };
        TipoDocumentoAtualizacao: components["schemas"]["TipoDocumentoInput"] & {
            ativo: boolean;
        };
        TipoDocumento: {
            /** Format: uuid */
            id: string;
            nome: string;
            instrucoes?: string | null;
            ativo: boolean;
            /** Format: date-time */
            criadoEm: string;
        };
        TipoDocumentoRef: {
            /** Format: uuid */
            id: string;
            nome: string;
            instrucoes?: string | null;
        };
        /** @description Visão da Jotanunes (inclui quem analisou). */
        Envio: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            empresaId: string;
            /** Format: uuid */
            tipoDocumentoId: string;
            nomeArquivo: string;
            formato: components["schemas"]["FormatoArquivo"];
            tamanhoBytes: number;
            /** Format: date-time */
            enviadoEm: string;
            status: components["schemas"]["StatusEnvio"];
            /** Format: date-time */
            analisadoEm?: string | null;
            analisadoPor?: components["schemas"]["AutorFluig"] | null;
            motivoRejeicao?: string | null;
        };
        EnvioFila: components["schemas"]["Envio"] & {
            empresa: components["schemas"]["EmpresaRef"];
            tipoDocumento: components["schemas"]["TipoDocumentoRef"];
        };
        PaginaEnvios: components["schemas"]["PaginaBase"] & {
            itens: components["schemas"]["EnvioFila"][];
        };
        Rejeicao: {
            /** @description Espaços nas pontas são removidos antes de validar. */
            motivo: string;
        };
        DocumentoSituacao: {
            tipoDocumento: components["schemas"]["TipoDocumentoRef"];
            situacao: components["schemas"]["SituacaoDocumento"];
            /** @description Envio que define a situação (null se PENDENTE_ENVIO). */
            envioAtual?: components["schemas"]["Envio"] | null;
            quantidadeEnvios?: number;
        };
        LoginInput: {
            cnpj: string;
            senha: string;
        };
        TrocaSenhaInput: {
            senhaAtual: string;
            /** @description Ao menos 1 letra e 1 número; diferente da atual. */
            novaSenha: string;
        };
        EmpresaPortal: {
            /** Format: uuid */
            id: string;
            razaoSocial: string;
            nomeFantasia?: string | null;
            cnpj: string;
            trocaSenhaObrigatoria: boolean;
        };
        SessaoPortal: {
            /** @description JWT portalAuth. */
            accessToken: string;
            /** Format: date-time */
            expiraEm: string;
            empresa: components["schemas"]["EmpresaPortal"];
        };
        /** @description Visão da empresa (NÃO inclui quem analisou). */
        EnvioPortal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tipoDocumentoId: string;
            nomeArquivo: string;
            formato: components["schemas"]["FormatoArquivo"];
            tamanhoBytes: number;
            /** Format: date-time */
            enviadoEm: string;
            status: components["schemas"]["StatusEnvio"];
            /** Format: date-time */
            analisadoEm?: string | null;
            motivoRejeicao?: string | null;
        };
        DocumentoSituacaoPortal: {
            tipoDocumento: components["schemas"]["TipoDocumentoRef"];
            situacao: components["schemas"]["SituacaoDocumento"];
            envioAtual?: components["schemas"]["EnvioPortal"] | null;
            /** @description true quando situação é PENDENTE_ENVIO ou REJEITADO. */
            podeEnviar: boolean;
        };
    };
    responses: {
        /** @description `VALIDACAO` — dados inválidos; `errors` traz as mensagens por campo */
        Validacao: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://jotanunes.com/problemas/validacao",
                 *       "title": "Confira os dados informados.",
                 *       "status": 400,
                 *       "code": "VALIDACAO",
                 *       "errors": {
                 *         "cnpj": [
                 *           "CNPJ inválido."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description `NAO_AUTENTICADO` — token ausente, inválido, expirado, revogado ou do outro esquema */
        NaoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description `TROCA_SENHA_OBRIGATORIA` — a empresa (portal) ou o usuário interno (login próprio da área Jotanunes) precisa trocar a senha antes de continuar */
        TrocaSenhaObrigatoria: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description `SEM_PERMISSAO` — operação só para administradores; o token (Fluig ou login próprio) não tem `roles` com `admin`. Com login próprio e troca de senha pendente, esta rota devolve antes `TROCA_SENHA_OBRIGATORIA` (mesmo status 403) */
        SemPermissao: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://jotanunes.com/problemas/sem-permissao",
                 *       "title": "Só administradores podem fazer isso. Se você precisa, fale com a TI.",
                 *       "status": 403,
                 *       "code": "SEM_PERMISSAO"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description `NAO_ENCONTRADO` — recurso inexistente ou de outra empresa */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description `LIMITE_REQUISICOES` — muitas tentativas; header Retry-After em segundos */
        LimiteRequisicoes: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description Conteúdo do arquivo. Headers: `Content-Disposition: attachment; filename*=UTF-8''<nome>`,
         *     `X-Content-Type-Options: nosniff`, `Cache-Control: no-store`.
         */
        Arquivo: {
            headers: {
                "Content-Disposition"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/pdf": string;
                "image/jpeg": string;
                "image/png": string;
            };
        };
    };
    parameters: {
        Pagina: number;
        TamanhoPagina: number;
        /** @description Trecho do nome, código ou cidade (sem diferenciar maiúsculas/acentos). */
        Busca: string;
        ObraId: string;
        EmpresaId: string;
        TipoDocumentoId: string;
        EnvioId: string;
        UsuarioId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API disponível */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    fluigObterUsuarioAtual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário atual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioFluig"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    fluigObterConfiguracaoAcesso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuração de acesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracaoAcesso"];
                };
            };
        };
    };
    fluigLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginJotanunesInput"];
            };
        };
        responses: {
            /** @description Autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoJotanunes"];
                };
            };
            400: components["responses"]["Validacao"];
            /** @description `LOGIN_INVALIDO` ou `SENHA_PROVISORIA_EXPIRADA` (senha certa, provisória vencida) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `USUARIO_INATIVO` (senha certa, usuário desativado) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            404: components["responses"]["NaoEncontrado"];
            /** @description `ACESSO_BLOQUEADO` (extensão `bloqueadoAte` com a data/hora de liberação) */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            429: components["responses"]["LimiteRequisicoes"];
        };
    };
    fluigTrocarSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrocaSenhaInput"];
            };
        };
        responses: {
            /** @description Senha trocada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoJotanunes"];
                };
            };
            /** @description `VALIDACAO`, `SENHA_FRACA` ou `SENHA_ATUAL_INCORRETA` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `SO_LOGIN_LOCAL` (sessão aberta pelo Fluig) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigSair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada (ou nada a fazer */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigObterPainel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicadores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Painel"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
        };
    };
    fluigListarObras: {
        parameters: {
            query?: {
                /** @description Trecho do nome, código ou cidade (sem diferenciar maiúsculas/acentos). */
                busca?: components["parameters"]["Busca"];
                /** @description Filtra por ativa/inativa. Omitido = todas. */
                ativa?: boolean;
                pagina?: components["parameters"]["Pagina"];
                tamanhoPagina?: components["parameters"]["TamanhoPagina"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de obras */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaObras"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
        };
    };
    fluigCriarObra: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObraInput"];
            };
        };
        responses: {
            /** @description Obra criada */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Obra"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            /** @description `CODIGO_OBRA_DUPLICADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigObterObra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obraId: components["parameters"]["ObraId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Obra */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObraDetalhe"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigAtualizarObra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obraId: components["parameters"]["ObraId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObraAtualizacao"];
            };
        };
        responses: {
            /** @description Obra atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Obra"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `CODIGO_OBRA_DUPLICADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigVincularEmpresaObra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obraId: components["parameters"]["ObraId"];
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vínculo existe (criado agora ou antes) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigDesvincularEmpresaObra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obraId: components["parameters"]["ObraId"];
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vínculo removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigListarEmpresas: {
        parameters: {
            query?: {
                /** @description Trecho da razão social, nome fantasia ou CNPJ (com ou sem máscara). */
                busca?: string;
                /** @description Somente empresas vinculadas a esta obra. */
                obraId?: string;
                situacaoAcesso?: components["schemas"]["SituacaoAcesso"];
                /** @description true = somente empresas com documento pendente de envio ou rejeitado. */
                comPendencia?: boolean;
                pagina?: components["parameters"]["Pagina"];
                tamanhoPagina?: components["parameters"]["TamanhoPagina"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de empresas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaEmpresas"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
        };
    };
    fluigCriarEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmpresaInput"];
            };
        };
        responses: {
            /** @description Empresa criada (situação de acesso `NAO_CONVIDADA`) */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Empresa"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            /** @description `CNPJ_DUPLICADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigObterEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empresa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Empresa"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigAtualizarEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmpresaAtualizacao"];
            };
        };
        responses: {
            /** @description Empresa atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Empresa"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `CNPJ_DUPLICADO` ou `CNPJ_IMUTAVEL` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigListarConvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Convite"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigEnviarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite enviado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Convite"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `EMPRESA_INATIVA` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `EMAIL_FALHOU` */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigListarDocumentosEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documentos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoSituacao"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigListarHistoricoEnvios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresaId: components["parameters"]["EmpresaId"];
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envio"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigListarTiposDocumento: {
        parameters: {
            query?: {
                /** @description Filtra por ativo/inativo. Omitido = todos. */
                ativo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tipos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDocumento"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
        };
    };
    fluigCriarTipoDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TipoDocumentoInput"];
            };
        };
        responses: {
            /** @description Tipo criado */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDocumento"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            /** @description `NOME_DUPLICADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigObterTipoDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tipo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDocumento"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigAtualizarTipoDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TipoDocumentoAtualizacao"];
            };
        };
        responses: {
            /** @description Tipo atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDocumento"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `NOME_DUPLICADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigListarEnvios: {
        parameters: {
            query?: {
                status?: components["schemas"]["StatusEnvio"];
                /** @description Envios de empresas vinculadas a esta obra. */
                obraId?: string;
                empresaId?: string;
                tipoDocumentoId?: string;
                pagina?: components["parameters"]["Pagina"];
                tamanhoPagina?: components["parameters"]["TamanhoPagina"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de envios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaEnvios"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
        };
    };
    fluigObterEnvio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvioFila"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigBaixarArquivoEnvio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Arquivo"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigAprovarEnvio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envio aprovado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envio"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `ENVIO_JA_ANALISADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigRejeitarEnvio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rejeicao"];
            };
        };
        responses: {
            /** @description Envio rejeitado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envio"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `ENVIO_JA_ANALISADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigListarUsuariosInternos: {
        parameters: {
            query?: {
                /** @description Trecho do nome, login ou e-mail (sem diferenciar maiúsculas/acentos). */
                busca?: string;
                /** @description Filtra por ativo/desativado. Omitido = todos. */
                ativo?: boolean;
                /** @description Filtra por perfil (true = administradores). Omitido = todos. */
                admin?: boolean;
                pagina?: components["parameters"]["Pagina"];
                tamanhoPagina?: components["parameters"]["TamanhoPagina"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de usuários internos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaUsuariosInternos"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
        };
    };
    fluigCriarUsuarioInterno: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioInternoInput"];
            };
        };
        responses: {
            /** @description Usuário criado (situação `AGUARDANDO_PRIMEIRO_ACESSO`) */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioInterno"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            /** @description `LOGIN_DUPLICADO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `EMAIL_ACESSO_FALHOU` */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigObterUsuarioInterno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: components["parameters"]["UsuarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário interno */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioInterno"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    fluigAtualizarUsuarioInterno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: components["parameters"]["UsuarioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioInternoAtualizacao"];
            };
        };
        responses: {
            /** @description Usuário atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioInterno"];
                };
            };
            400: components["responses"]["Validacao"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `ULTIMO_ADMINISTRADOR` ou `ALTERACAO_PROPRIA_NAO_PERMITIDA` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    fluigRedefinirSenhaUsuarioInterno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: components["parameters"]["UsuarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Senha redefinida (situação `AGUARDANDO_PRIMEIRO_ACESSO`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioInterno"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `USUARIO_INATIVO` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `EMAIL_ACESSO_FALHOU` */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    portalValidarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConviteValidacaoInput"];
            };
        };
        responses: {
            /** @description Convite válido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConviteValidacao"];
                };
            };
            400: components["responses"]["Validacao"];
            /** @description `CONVITE_INVALIDO` (inexistente, expirado, usado ou substituído) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            429: components["responses"]["LimiteRequisicoes"];
        };
    };
    portalLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoPortal"];
                };
            };
            400: components["responses"]["Validacao"];
            /** @description `CREDENCIAIS_INVALIDAS` ou `CONVITE_EXPIRADO` (senha temporária vencida) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `EMPRESA_INATIVA` (credenciais corretas, empresa desativada) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `ACESSO_BLOQUEADO` (extensão `bloqueadoAte` com a data/hora de liberação) */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            429: components["responses"]["LimiteRequisicoes"];
        };
    };
    portalTrocarSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrocaSenhaInput"];
            };
        };
        responses: {
            /** @description Senha trocada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoPortal"];
                };
            };
            /** @description `VALIDACAO`, `SENHA_FRACA` ou `SENHA_ATUAL_INCORRETA` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    portalObterEmpresaAtual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empresa atual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaPortal"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    portalListarDocumentos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documentos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoSituacaoPortal"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
        };
    };
    portalListarHistoricoEnvios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvioPortal"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
    portalEnviarDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipoDocumentoId: components["parameters"]["TipoDocumentoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description Envio registrado (status `EM_ANALISE`) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvioPortal"];
                };
            };
            /** @description `VALIDACAO` (campo ausente) ou `ARQUIVO_INVALIDO` (vazio/corrompido) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
            /** @description `ENVIO_NAO_PERMITIDO` (documento em análise ou aprovado) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `ARQUIVO_MUITO_GRANDE` */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description `ARQUIVO_TIPO_NAO_SUPORTADO` */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    portalBaixarArquivoEnvio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                envioId: components["parameters"]["EnvioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Arquivo"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["TrocaSenhaObrigatoria"];
            404: components["responses"]["NaoEncontrado"];
        };
    };
}
