// <auto-generated />
using System;
using Jotanunes.Docs.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jotanunes.Docs.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(DocsDbContext))]
    [Migration("20260929144808_PerfilAdminAuditoria")]
    partial class PerfilAdminAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jotanunes.Docs.Domain.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("acao");

                    b.Property<bool?>("AtorAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("ator_admin");

                    b.Property<string>("AtorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ator_id");

                    b.Property<string>("AtorTipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ator_tipo");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("RecursoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recurso_id");

                    b.Property<string>("RecursoTipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("recurso_tipo");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("OcorridoEm")
                        .HasDatabaseName("ix_auditoria_ocorrido_em");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Convites.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailDestino")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_destino");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("EnviadoPorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("enviado_por_login");

                    b.Property<string>("EnviadoPorNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("enviado_por_nome");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<DateTimeOffset?>("SubstituidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("substituido_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.HasKey("Id")
                        .HasName("pk_convites");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_convites_token_hash");

                    b.HasIndex("EmpresaId", "EnviadoEm")
                        .HasDatabaseName("ix_convites_empresa_id_enviado_em");

                    b.ToTable("convites", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por_login");

                    b.Property<DateTimeOffset?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("char(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por_login");

                    b.Property<string>("EmailContato")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_contato");

                    b.Property<string>("NomeContato")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_contato");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTimeOffset?>("SenhaTemporariaExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("senha_temporaria_expira_em");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_falhas");

                    b.Property<bool>("TrocaSenhaObrigatoria")
                        .HasColumnType("boolean")
                        .HasColumnName("troca_senha_obrigatoria");

                    b.Property<DateTimeOffset?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.Property<int>("VersaoCredencial")
                        .HasColumnType("integer")
                        .HasColumnName("versao_credencial");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_cnpj");

                    b.HasIndex("RazaoSocial")
                        .HasDatabaseName("ix_empresas_razao_social");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Empresas.TentativasLoginCnpj", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("char(64)")
                        .HasColumnName("chave");

                    b.Property<DateTimeOffset?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_falhas");

                    b.Property<DateTimeOffset?>("UltimaFalhaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_falha_em");

                    b.HasKey("Chave")
                        .HasName("pk_tentativas_login");

                    b.ToTable("tentativas_login", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Envios.EnvioDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnalisadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analisado_em");

                    b.Property<string>("AnalisadoPorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("analisado_por_login");

                    b.Property<string>("AnalisadoPorNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("analisado_por_nome");

                    b.Property<string>("ChaveArmazenamento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("chave_armazenamento");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("pk_envios_documento");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("ix_envios_documento_tipo_documento_id");

                    b.HasIndex("EmpresaId", "TipoDocumentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_envios_documento_vivo")
                        .HasFilter("status <> 'REJEITADO'");

                    b.HasIndex("Status", "EnviadoEm")
                        .HasDatabaseName("ix_envios_documento_status_enviado");

                    b.HasIndex("EmpresaId", "TipoDocumentoId", "EnviadoEm")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_envios_documento_empresa_tipo_enviado");

                    b.ToTable("envios_documento", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Obras.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por_login");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por_login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_obras");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_obras_nome");

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Obras.ObraEmpresa", b =>
                {
                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid")
                        .HasColumnName("obra_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("VinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vinculado_em");

                    b.Property<string>("VinculadoPorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vinculado_por_login");

                    b.HasKey("ObraId", "EmpresaId")
                        .HasName("pk_obra_empresas");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_obra_empresas_empresa_id");

                    b.ToTable("obra_empresas", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.TiposDocumento.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por_login");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por_login");

                    b.Property<string>("Instrucoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instrucoes");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipos_documento");

                    b.ToTable("tipos_documento", (string)null);
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Convites.Convite", b =>
                {
                    b.HasOne("Jotanunes.Docs.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_convites_empresas_empresa_id");
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Envios.EnvioDocumento", b =>
                {
                    b.HasOne("Jotanunes.Docs.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_envios_documento_empresas_empresa_id");

                    b.HasOne("Jotanunes.Docs.Domain.TiposDocumento.TipoDocumento", null)
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_envios_documento_tipos_documento_tipo_documento_id");
                });

            modelBuilder.Entity("Jotanunes.Docs.Domain.Obras.ObraEmpresa", b =>
                {
                    b.HasOne("Jotanunes.Docs.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_obra_empresas_empresas_empresa_id");

                    b.HasOne("Jotanunes.Docs.Domain.Obras.Obra", null)
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_obra_empresas_obras_obra_id");
                });
#pragma warning restore 612, 618
        }
    }
}
